import {RoleModel} from './rolemodel';
import {onetomany, manytoone, manytomany} from 'nodedata/core/decorators'; 
import {field, document} from 'nodedata/mongoose/decorators';
import {IUser} from './user';
import {Types} from 'mongoose';
import {Strict} from 'nodedata/mongoose/enums';

@document({ name: 'teacher', strict: Strict.true })
export class TeacherModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: string;

    @field({ itemType: String})
    courses: Array<string>;

}
export default TeacherModel;